version: '2'

services:  
  mysql:
    build:
      context: ./mysql-docker
    volumes:
      - ~/tmp/mysql_data:/var/lib/mysql
  web:
    build:
      context: ./wordpress-docker
      dockerfile: Dockerfile-compose
    volumes:
      - ~/tmp/wordpress_data:/var/www/html
    links:
      - mysql
    ports:
      - "8080:80"         
#  nginx:
#    build:
#      context: ./nginx-docker
#    ports:
#      - "8080:80"      
#    links:
#      - app
