apiVersion: v1
kind: Service
metadata:
  name: lb-app3
  labels:
    app: lb-app3
    tier: backend
spec:
  type: NodePort
  ports:
    # the port that this service should serve on
  - port: 8080
  selector:
    app: lb-app3
    tier: backend 